# Generated by Django 3.2.3 on 2021-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='Profile/%Y/%m/%d/images')),
                ('iurl', models.URLField(max_length=32)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
