# Generated by Django 3.2.3 on 2021-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pSELLER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50)),
                ('pnumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('repassword', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=100)),
                ('iurl', models.URLField(max_length=150)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sample1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flname', models.CharField(max_length=30)),
                ('pnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('repassword', models.CharField(max_length=32)),
            ],
        ),
    ]
